language: php
dist: precise
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests

script: phpunit -v
  - cd ../
##  - git init
  - git config --global user.name "yakeing"
  - git config --global user.email "yakeing@gmail.com"
  - git tag v3.0
  - git show v3.0
  - git push --force --quiet "https://${TOKEN}@github.com/yakeing/str_increment.git" master:master
